def write_prompt():
    print("\n******************* Menu *******************")
    print("Ajouter un client                  : 1")
    print("Rechercher un client par email     : 2")
    print("\nAjouter une destination            : 3")
    print("Mettre a jour une destination      : 4")
    print("Rechercher une destination par nom : 5")
    print("\nCreer une reservation              : 6")
    print("Anuler une reservation             : 7")
    print("Afficher les reservation           : 8")
    print("\nQuitter                            : Q / q")
    print("--------------------------------------------")
